# Generated by Django 4.2.23 on 2025-07-31 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_consumed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumed',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='consumed',
            name='date',
        ),
    ]
